### ISSUE TITLE
[BUG]: error when using scenario from github

### ISSUE THREAD

**Issue by EmilieEPLoire** [Guts/qgis-deployment-cli#232]
### Is there an existing issue or a documentation page for this?

- [X] I have searched the existing issues and within documentation

### Which version of the app are you using?

0-21-3

### Operating System

Windows 10+*

### Packaging mode

Stand-alone executable (.i.e qdt.exe)

### Description of the bug

using qdt whith url "https://github.com/eptb-loire/qgis_profiles/blob/main/qdt_scenarii/scenario.qdt.yml" doesn't work.
Usign with the same file in local works.

### Relevant log output

```Shell
PS Z:\installqgis> .\QGISDeploymentToolbelt_0-21-3_Windows64bit_Python3-11.exe -s scenario.qdt.yml -v
2023-03-10 15:38:34||INFO||deployment||Running scenario: Profile EP Loire (eploire_utilisateur). ScÃ©nario de deploiement des profils utilisateurs, basÃ©s sur des secteurs gÃ©ographiques.
2023-03-10 15:38:34||INFO||deployment||QDT working folder: C:\Users\ebigorne\.cache\qgis-deployment-toolbelt\eploire
2023-03-10 15:38:34||INFO||deployment||Running step: qprofiles-manager
2023-03-10 15:38:34||INFO||remote_git_handler||Fetching repository https://github.com/eptb-loire/qgis_profiles.git to C:\Users\ebigorne\.cache\qgis-deployment-toolbelt\default
2023-03-10 15:38:34||INFO||remote_git_handler||Pulling repository https://github.com/eptb-loire/qgis_profiles.git to C:\Users\ebigorne\.cache\qgis-deployment-toolbelt\default
2023-03-10 15:38:35||INFO||job_profiles_synchronizer||7 downloaded profiles: axe_loire, cadastre, cher, haut_bassin, loire_aval, maine, support
2023-03-10 15:38:35||INFO||job_profiles_synchronizer||All installed profiles are the same as downloaded ones: 7
2023-03-10 15:38:35||INFO||deployment||Running step: qplugins-downloader
2023-03-10 15:38:35||INFO||job_plugins_downloader||QDT plugins folder: C:\Users\ebigorne\.cache\qgis-deployment-toolbelt\plugins
2023-03-10 15:38:35||ERROR||file_downloader||Downloading S:/Commun_DDRE/donnees%26outils/Consult_donnees/plugin/indic_spi.zip to C:\Users\ebigorne\.cache\qgis-deployment-toolbelt\plugins\indicateur-spi_0-1.zip failed. Cause: URLError. Trace: <urlopen error unknown url type: s>
2023-03-10 15:38:35||ERROR||file_downloader||Downloading S:/Commun_DDRE/donnees%26outils/Consult_donnees/plugin/piezo_stat.zip to C:\Users\ebigorne\.cache\qgis-deployment-toolbelt\plugins\piezo-stat_0-2.zip failed. Cause: URLError. Trace: <urlopen error unknown url type: s>
2023-03-10 15:38:35||INFO||deployment||Running step: qplugins-synchronizer
2023-03-10 15:38:35||INFO||job_plugins_synchronizer||QDT plugins folder: C:\Users\ebigorne\.cache\qgis-deployment-toolbelt\plugins
2023-03-10 15:38:35||WARNING||job_plugins_synchronizer||Profile axe_loire - Plugin Indicateur SPI version 0.1 should be installed but its archive is not found: C:\Users\ebigorne\.cache\qgis-deployment-toolbelt\plugins\indicateur-spi_0-1.zip
2023-03-10 15:38:35||WARNING||job_plugins_synchronizer||Profile axe_loire - Plugin piezo stat version 0.2 should be installed but its archive is not found: C:\Users\ebigorne\.cache\qgis-deployment-toolbelt\plugins\piezo-stat_0-2.zip
2023-03-10 15:38:35||WARNING||job_plugins_synchronizer||Profile cher - Plugin Indicateur SPI version 0.1 should be installed but its archive is not found: C:\Users\ebigorne\.cache\qgis-deployment-toolbelt\plugins\indicateur-spi_0-1.zip
2023-03-10 15:38:35||WARNING||job_plugins_synchronizer||Profile cher - Plugin piezo stat version 0.2 should be installed but its archive is not found: C:\Users\ebigorne\.cache\qgis-deployment-toolbelt\plugins\piezo-stat_0-2.zip
2023-03-10 15:38:35||WARNING||job_plugins_synchronizer||Profile haut_bassin - Plugin Indicateur SPI version 0.1 should be installed but its archive is not found: C:\Users\ebigorne\.cache\qgis-deployment-toolbelt\plugins\indicateur-spi_0-1.zip
2023-03-10 15:38:35||WARNING||job_plugins_synchronizer||Profile haut_bassin - Plugin piezo stat version 0.2 should be installed but its archive is not found: C:\Users\ebigorne\.cache\qgis-deployment-toolbelt\plugins\piezo-stat_0-2.zip
2023-03-10 15:38:35||WARNING||job_plugins_synchronizer||Profile loire_aval - Plugin Indicateur SPI version 0.1 should be installed but its archive is not found: C:\Users\ebigorne\.cache\qgis-deployment-toolbelt\plugins\indicateur-spi_0-1.zip
2023-03-10 15:38:35||WARNING||job_plugins_synchronizer||Profile loire_aval - Plugin piezo stat version 0.2 should be installed but its archive is not found: C:\Users\ebigorne\.cache\qgis-deployment-toolbelt\plugins\piezo-stat_0-2.zip
2023-03-10 15:38:35||WARNING||job_plugins_synchronizer||Profile maine - Plugin Indicateur SPI version 0.1 should be installed but its archive is not found: C:\Users\ebigorne\.cache\qgis-deployment-toolbelt\plugins\indicateur-spi_0-1.zip
2023-03-10 15:38:35||WARNING||job_plugins_synchronizer||Profile maine - Plugin piezo stat version 0.2 should be installed but its archive is not found: C:\Users\ebigorne\.cache\qgis-deployment-toolbelt\plugins\piezo-stat_0-2.zip
2023-03-10 15:38:35||WARNING||job_plugins_synchronizer||Profile support - Plugin Indicateur SPI version 0.1 should be installed but its archive is not found: C:\Users\ebigorne\.cache\qgis-deployment-toolbelt\plugins\indicateur-spi_0-1.zip
2023-03-10 15:38:35||WARNING||job_plugins_synchronizer||Profile support - Plugin piezo stat version 0.2 should be installed but its archive is not found: C:\Users\ebigorne\.cache\qgis-deployment-toolbelt\plugins\piezo-stat_0-2.zip
2023-03-10 15:38:35||INFO||job_plugins_synchronizer||Profile maine - Plugin French Locator Filter 1.0.4 has been unzipped from C:\Users\ebigorne\.cache\qgis-deployment-toolbelt\plugins\1846_french-locator-filter_1-0-4.zip to C:\Users\ebigorne\AppData\Roaming\QGIS\QGIS3\profiles\maine\python\plugins
2023-03-10 15:38:35||INFO||deployment||Running step: splash-screen-manager
2023-03-10 15:38:35||WARNING||job_splash_screen||Profile axe_loire -C:\Users\ebigorne\AppData\Roaming\QGIS\QGIS3\profiles\axe_loire\images\splash.png dimensions (668, 253) do not comply with  dimensions recomended by QGIS for splash screen: 600x300.
2023-03-10 15:38:35||WARNING||job_splash_screen||Profile cadastre -C:\Users\ebigorne\AppData\Roaming\QGIS\QGIS3\profiles\cadastre\images\splash.png dimensions (659, 296) do not comply with  dimensions recomended by QGIS for splash screen: 600x300.
2023-03-10 15:38:35||WARNING||job_splash_screen||Profile cher -C:\Users\ebigorne\AppData\Roaming\QGIS\QGIS3\profiles\cher\images\splash.png dimensions (775, 311) do not comply with  dimensions recomended by QGIS for splash screen: 600x300.
2023-03-10 15:38:35||WARNING||job_splash_screen||Profile haut_bassin -C:\Users\ebigorne\AppData\Roaming\QGIS\QGIS3\profiles\haut_bassin\images\splash.png dimensions (624, 261) do not comply with  dimensions recomended by QGIS for splash screen: 600x300.
2023-03-10 15:38:35||WARNING||job_splash_screen||Profile Loire_aval -C:\Users\ebigorne\AppData\Roaming\QGIS\QGIS3\profiles\Loire_aval\images\splash.png dimensions (638, 283) do not comply with  dimensions recomended by QGIS for splash screen: 600x300.
2023-03-10 15:38:35||WARNING||job_splash_screen||Profile maine -C:\Users\ebigorne\AppData\Roaming\QGIS\QGIS3\profiles\maine\images\splash.png dimensions (635, 290) do not comply with  dimensions recomended by QGIS for splash screen: 600x300.
2023-03-10 15:38:35||WARNING||job_splash_screen||Profile support -C:\Users\ebigorne\AppData\Roaming\QGIS\QGIS3\profiles\support\images\splash.png dimensions (633, 225) do not comply with  dimensions recomended by QGIS for splash screen: 600x300.
2023-03-10 15:38:35||INFO||deployment||Running step: shortcuts-manager
2023-03-10 15:38:35||INFO||job_shortcuts||Created shortcut Qgis Axe Loire
2023-03-10 15:38:35||INFO||job_shortcuts||Created shortcut Qgis Bassin du Cher
2023-03-10 15:38:35||INFO||job_shortcuts||Created shortcut Qgis Allier et Loire amont
2023-03-10 15:38:35||INFO||job_shortcuts||Created shortcut Qgis Loire aval
2023-03-10 15:38:35||INFO||job_shortcuts||Created shortcut Qgis Bassin de la Maine
2023-03-10 15:38:35||INFO||job_shortcuts||Created shortcut Qgis essentiel BV Loire
2023-03-10 15:38:35||INFO||bouncer||Deployment achieved!
PS Z:\installqgis> $env:QDT_SCENARIO_PATH="https://github.com/eptb-loire/qgis_profiles/blob/main/qdt_scenarii/scenario.qdt.yml"
PS Z:\installqgis> .\QGISDeploymentToolbelt_0-21-3_Windows64bit_Python3-11.exe -v
2023-03-10 15:40:55||WARNING||file_downloader||downloaded_scenario.qdt.yml already exists. It's about to be replaced.
2023-03-10 15:40:56||INFO||file_downloader||Downloading https://github.com/eptb-loire/qgis_profiles/blob/main/qdt_scenarii/scenario.qdt.yml to downloaded_scenario.qdt.yml succeeded.
Traceback (most recent call last):
  File "qgis_deployment_toolbelt\cli.py", line 196, in <module>
  File "qgis_deployment_toolbelt\cli.py", line 183, in main
  File "qgis_deployment_toolbelt\commands\deployment.py", line 97, in run
  File "qgis_deployment_toolbelt\scenarios\scenario_reader.py", line 51, in __init__
  File "yaml\__init__.py", line 125, in safe_load
  File "yaml\__init__.py", line 81, in load
  File "yaml\constructor.py", line 49, in get_single_data
  File "yaml\composer.py", line 36, in get_single_node
  File "yaml\composer.py", line 58, in compose_document
  File "yaml\parser.py", line 118, in get_event
  File "yaml\parser.py", line 193, in parse_document_end
  File "yaml\scanner.py", line 129, in peek_token
  File "yaml\scanner.py", line 223, in fetch_more_tokens
  File "yaml\scanner.py", line 577, in fetch_value
yaml.scanner.ScannerError: mapping values are not allowed here
  in "downloaded_scenario.qdt.yml", line 27, column 66
[12108] Failed to execute script 'cli' due to unhandled exception!
```

**Comment by Guts** [comment]
Thanks @EmilieEPLoire for reporting!

The hyperlink you provide points to a HTML page showing a YAML file: https://github.com/eptb-loire/qgis_profiles/blob/main/qdt_scenarii/scenario.qdt.yml

You migh want to use: https://raw.githubusercontent.com/eptb-loire/qgis_profiles/main/qdt_scenarii/scenario.qdt.yml

**Comment by EmilieEPLoire** [comment]
it works. Thanks
