### ISSUE TITLE
[BUG]: export-rules-context sur Windows

### ISSUE THREAD

**Issue by afourneyron** [Guts/qgis-deployment-cli#506]
### Is there an existing issue or a documentation page for this?

- [X] I have searched the existing issues and within documentation

### Which version of the app are you using?

0-34-2

### Operating System

Windows 10+*

### Packaging mode

Stand-alone executable (.i.e qdt.exe)

### Related resources

https://github.com/lpoaura/lpo_qgis_profiles

### Description of the bug

```sh
qdt export-rules-context
```

```python
2024-05-28 15:15:47||ERROR||bouncer||exit_cli_error||43||Either a distinguished name or a COM object must be provided to create an ADObject
Traceback (most recent call last):
  File "C:\Users\afourneyron\Documents\lpo_qgis_profiles\lpo_qgis_profiles\.venv\Lib\site-packages\qgis_deployment_toolbelt\commands\cmd_rules_context.py", line 85, in run
    wf.write(rules_context.to_json(indent=4, sort_keys=True))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\afourneyron\Documents\lpo_qgis_profiles\lpo_qgis_profiles\.venv\Lib\site-packages\qgis_deployment_toolbelt\profiles\rules_context.py", line 151, in to_json
    obj_as_dict = self.to_dict()
                  ^^^^^^^^^^^^^^
  File "C:\Users\afourneyron\Documents\lpo_qgis_profiles\lpo_qgis_profiles\.venv\Lib\site-packages\qgis_deployment_toolbelt\profiles\rules_context.py", line 129, in to_dict
    result[attr.removeprefix("_context_")] = getattr(self, attr)
                                             ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\afourneyron\Documents\lpo_qgis_profiles\lpo_qgis_profiles\.venv\Lib\site-packages\qgis_deployment_toolbelt\profiles\rules_context.py", line 113, in _context_user
    "groups_domain": get_user_domain_groups(),
                     ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\afourneyron\Documents\lpo_qgis_profiles\lpo_qgis_profiles\.venv\Lib\site-packages\qgis_deployment_toolbelt\utils\user_groups.py", line 120, in get_user_domain_groups
    user_obj = pyad.aduser.ADUser.from_cn(user_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\afourneyron\Documents\lpo_qgis_profiles\lpo_qgis_profiles\.venv\Lib\site-packages\pyad\adobject.py", line 152, in from_cn
    return cls(adsearch.by_cn(cn, search_base, options), None, options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\afourneyron\Documents\lpo_qgis_profiles\lpo_qgis_profiles\.venv\Lib\site-packages\pyad\adobject.py", line 105, in __init__
    raise Exception(
Exception: Either a distinguished name or a COM object must be provided to create an ADObject
2024-05-28 15:15:47||ERROR||bouncer||exit_cli_error||44||Please, read the full detailed log: C:\Users\afourneyron\.cache\qgis-deployment-toolbelt\logs\QGISDeploymentToolbelt_0.34.2.log
Either a distinguished name or a COM object must be provided to create an ADObject
```

### Steps to reproduce

1. ouvrir le terminal et lancer la commande .\Downloads\Windows_QGISDeploymentToolbelt_0-34-2.exe export-rules-context
2. lancer la commande dans un environnement virtuel sur Python même problème.

**Comment by Guts** [comment]
Thanks for your interest and taking time to report here.  
Fixed in https://github.com/Guts/qgis-deployment-cli/releases/tag/0.34.3?notification_referrer_id=NT_kwDOABhbPrMxMDg2MzA2MzA4MjoxNTk2MjIy
